on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    name: Hello World Job
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
    steps:
      - name: Print Date
        run: |
          date
    steps:
      - name: List Directory
        run: |
          ls