name: Testing stuff

on:
  push:
    branches:
      - message

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#skip') == false }}
        env:
          MESSAGE: ${{ join(github.event.commits.*.message) }} 
          TRUE_OR_NOT: ${{ contains(join(github.event.commits.*.message), 'fix') }}        
        run: echo "$MESSAGE"
